spring:
  application:
      name: Config-Dev
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaullZone: ${eureka_url:http://192.168.1.8:8761/eureka}
  instance:
    hostname: 192.168.1.8:8761
    prefer-ip-address: true
